<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
<style>



</style>

<div class="footer content">
<div class="footer-container">
	
    <div class="footer">
 		<div>
			<h3>ABOUT</h3>
			<ul>
				<li><a href="/shows-and-events/">Shows &amp; Events</a></li>
                <li><a href="" target="_blank">Service</a></li>
                <li><a href="/contact-us/">Branches</a></li>
	        </ul>
    	</div>
    	<div>
			<h3>QUICK LINKS</h3>
			<ul>
				
	        </ul>
		</div>
		<div>
			<h3>TERMS & CONDITIONS</h3>
			
	       
    	</div>
		<div>
			<h3>CONTACT</h3>
			
	        
		</div>
		
		
    </div>
</div>
	</div>
